name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.19

  test:
    name: Test setup-postgresql
    runs-on: ${{ matrix.platform }}
    concurrency: ${{ matrix.platform }}-${{ matrix.postgresql_version }}-${{ github.ref }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-20.04, macos-latest, macos-11, macos-13, windows-latest]
        postgresql_version: [10, 11, 12, 14, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Run setup-postgresql
        uses: ./
        with:
          postgresql-version: ${{ matrix.postgresql_version }}
      - name: Verify PostgreSQL
        run: |
          pg_dump --version
          psql --version
          pg_restore --version
